# Generated by Django 4.2.1 on 2023-06-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_Profesion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Profesion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Profesional',
            fields=[
                ('id_Usuario_Profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('foto_perfil', models.ImageField(upload_to='')),
                ('telefono', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('calificacion_obtenida', models.FloatField()),
                ('ciudad_id', models.IntegerField()),
                ('rol_id', models.IntegerField()),
                ('profesion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflix_app_venv.profesion')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflix_app_venv.provincia')),
            ],
        ),
    ]
